/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 c:/Users/Perez/Desktop/Desarrollo/Modelo_LSP/modelo_lstm_lsp/app_web/static/models/avatar/body.glb --types 
*/

import * as THREE from 'three'
import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF, SkeletonUtils } from 'three-stdlib'

type ActionName = 'Armature|mixamo.com|Layer0' | 'Armature|mixamo.com|Layer0.001'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    Body: THREE.SkinnedMesh
    Bottoms: THREE.SkinnedMesh
    Eyelashes: THREE.SkinnedMesh
    Eyes: THREE.SkinnedMesh
    Hair: THREE.SkinnedMesh
    Shoes: THREE.SkinnedMesh
    Tops: THREE.SkinnedMesh
    mixamorigHips: THREE.Bone
  }
  materials: {
    ['Bodymat.001']: THREE.MeshStandardMaterial
    ['Bottommat.001']: THREE.MeshStandardMaterial
    ['Eyelashmat.001']: THREE.MeshStandardMaterial
    ['Hairmat.001']: THREE.MeshStandardMaterial
    ['Shoesmat.001']: THREE.MeshStandardMaterial
    ['Topmat.001']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const group = React.useRef<THREE.Group>()
  const { scene, animations } = useGLTF('/body.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone) as GLTFResult
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes.mixamorigHips} />
          <skinnedMesh name="Body" geometry={nodes.Body.geometry} material={materials['Bodymat.001']} skeleton={nodes.Body.skeleton} />
          <skinnedMesh name="Bottoms" geometry={nodes.Bottoms.geometry} material={materials['Bottommat.001']} skeleton={nodes.Bottoms.skeleton} />
          <skinnedMesh name="Eyelashes" geometry={nodes.Eyelashes.geometry} material={materials['Eyelashmat.001']} skeleton={nodes.Eyelashes.skeleton} />
          <skinnedMesh name="Eyes" geometry={nodes.Eyes.geometry} material={materials['Bodymat.001']} skeleton={nodes.Eyes.skeleton} />
          <skinnedMesh name="Hair" geometry={nodes.Hair.geometry} material={materials['Hairmat.001']} skeleton={nodes.Hair.skeleton} />
          <skinnedMesh name="Shoes" geometry={nodes.Shoes.geometry} material={materials['Shoesmat.001']} skeleton={nodes.Shoes.skeleton} />
          <skinnedMesh name="Tops" geometry={nodes.Tops.geometry} material={materials['Topmat.001']} skeleton={nodes.Tops.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/body.glb')
